<a href="https://colab.research.google.com/github/kunj1674/Spotify_Analysis/blob/master/Spotify_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
path = '/content/drive/MyDrive/Spotify_Analysis/track_data_final.csv'
df=pd.read_csv(path)

In [ ]:
df.head(11)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album
5,7H0ya83CMmgFcOhw0UB6ow,Space Song,3,77,320466,False,Beach House,72.0,2803036.0,['dream pop'],194CqC2Zi0kUFEPWedb3qr,Depression Cherry,2015-08-28,9,album
6,41zXlQxzTi6cGAjpOXyLYH,idontwannabeyouanymore,2,78,203569,False,Billie Eilish,90.0,118692183.0,[],7fRrTyKvE4Skh93v97gtcU,dont smile at me,2017-12-22,9,single
7,13jRFAGT8qd6aBwtJySlUm,Allein Allein - BENNETT Remix,1,52,145977,False,Alok,76.0,11247155.0,"['brazilian bass', 'electronic', 'slap house',...",1WKoDELzbFRR6UWNGh50LO,Allein Allein (feat. FREY) [BENNETT Remix],2024-09-27,2,single
8,0N5zjRnf8AreOm95iSBXF4,Even My Dad Does Sometimes,15,50,228533,False,Ed Sheeran,88.0,122773292.0,['soft pop'],1xn54DMo2qIqBuMqHtUsFd,x (Deluxe Edition),2014-06-21,16,album
9,0qUcpOOna3kkrwfqky85e1,Eyes Blue Like The Atlantic (feat. Subvrbs),1,63,154599,False,Sista Prod,48.0,68226.0,[],5UYjxc4HIYeesKS0WJlhEI,Eyes Blue Like The Atlantic (feat. Subvrbs),2020-07-20,1,single
10,5JLv62qFIS1DR3zGEcApRt,Wide Awake,15,75,220946,False,Katy Perry,83.0,38385499.0,['pop'],5BvgP623rtvlc0HDcpzquz,Teenage Dream: The Complete Confection,2012-03-12,19,album

In [ ]:
df.shape

(8778, 15)

In [ ]:
df.columns

Index(['track_id', 'track_name', 'track_number', 'track_popularity',
       'track_duration_ms', 'explicit', 'artist_name', 'artist_popularity',
       'artist_followers', 'artist_genres', 'album_id', 'album_name',
       'album_release_date', 'album_total_tracks', 'album_type'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8778 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8778 non-null   object
 1   track_name          8776 non-null   object
 2   track_number        8778 non-null   int64
 3   track_popularity    8778 non-null   int64
 4   track_duration_ms   8778 non-null   int64
 5   explicit            8778 non-null   bool
 6   artist_name         8774 non-null   object
 7   artist_popularity   8774 non-null   float64
 8   artist_followers    8774 non-null   float64
 9   artist_genres       8774 non-null   object
 10  album_id            8778 non-null   object
 11  album_name          8776 non-null   object
 12  album_release_date  8778 non-null   object
 13  album_total_tracks  8778 non-null   int64
 14  album_type          8778 non-null   object
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 968.8+ KB

In [ ]:
df.describe()

,track_number,track_popularity,track_duration_ms,artist_popularity,artist_followers,album_total_tracks
count,8778.000000,8778.000000,8778.000000,8774.000000,8.774000e+03,8778.000000
mean,5.749487,52.232855,210157.791866,69.954981,2.435487e+07,13.779790
std,6.017938,24.075221,63326.841454,19.532783,3.813769e+07,11.797943
min,1.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000
25%,1.000000,39.000000,173921.250000,60.000000,5.152768e+05,6.000000
50%,4.000000,58.000000,207276.000000,74.000000,6.272266e+06,13.000000
75%,9.000000,71.000000,239693.250000,84.000000,3.055055e+07,17.000000
max,102.000000,100.000000,811077.000000,100.000000,1.455421e+08,181.000000

**Checking And Droping all the Null Value**

In [ ]:
df.isnull().sum()

track_id              0
track_name            2
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
album_id              0
album_name            2
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.shape

(8772, 15)

**Checking for the duplicadted values**

In [ ]:
df.duplicated().sum()

np.int64(0)

**Converting Column's datatype in proper format**

In [ ]:
#Converting release date from object to datetime
df['album_release_date']=pd.to_datetime(df['album_release_date'], format='mixed')

In [ ]:
#Converting genre string list into actual Python List
df['artist_genres'] = df['artist_genres'].apply(eval)

In [ ]:
#Converting album_type to category
df['album_type'] = df['album_type'].astype('category')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8772 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8772 non-null   object
 1   track_name          8772 non-null   object
 2   track_number        8772 non-null   int64
 3   track_popularity    8772 non-null   int64
 4   track_duration_ms   8772 non-null   int64
 5   explicit            8772 non-null   bool
 6   artist_name         8772 non-null   object
 7   artist_popularity   8772 non-null   float64
 8   artist_followers    8772 non-null   float64
 9   artist_genres       8772 non-null   object
 10  album_id            8772 non-null   object
 11  album_name          8772 non-null   object
 12  album_release_date  8772 non-null   datetime64[ns]
 13  album_total_tracks  8772 non-null   int64
 14  album_type          8772 non-null   category
dtypes: bool(1), category(1), datetime64[ns](1), float64(2), int64(4), object(6)
memory usage: 976.7+ KB

**Extract Year, Month, Day, and Day Name from album_release_date**

In [ ]:
df['release_year'] = df['album_release_date'].dt.year
df['release_month'] = df['album_release_date'].dt.month
df['release_day'] = df['album_release_date'].dt.day
df['release_day_name'] = df['album_release_date'].dt.day_name()

In [ ]:
df.head()

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,release_year,release_month,release_day,release_day_name
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,[pop],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation,2009,11,9,Monday
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,[stutter house],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single,2023,1,13,Friday
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album,2021,4,9,Friday
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album,2021,7,30,Friday
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album,2010,1,1,Friday

**Adding Duration of tracks in minutes and in MM:SS format**

In [ ]:
df['track_duration_min'] = (df['track_duration_ms'] / 60000).round(2)

In [ ]:
#Adding a column for duration format as 'MM:SS'
minutes = df['track_duration_ms'] // 60000
seconds = (df['track_duration_ms'] % 60000) // 1000
df['track_duration_mmss'] = minutes.astype(str).str.zfill(2) + ':' + seconds.astype(str).str.zfill(2)

In [ ]:
df.head(7)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,...,album_name,album_release_date,album_total_tracks,album_type,release_year,release_month,release_day,release_day_name,track_duration_min,track_duration_mmss
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,[pop],...,The Singles Collection,2009-11-09,58,compilation,2009,11,9,Monday,3.55,03:33
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,[stutter house],...,Clouds,2023-01-13,1,single,2023,1,13,Friday,2.65,02:38
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],...,Fearless (Taylor's Version),2021-04-09,26,album,2021,4,9,Friday,3.76,03:45
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],...,Happier Than Ever,2021-07-30,16,album,2021,7,30,Friday,2.64,02:38
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],...,Loud,2010-01-01,13,album,2010,1,1,Friday,4.45,04:27
5,7H0ya83CMmgFcOhw0UB6ow,Space Song,3,77,320466,False,Beach House,72.0,2803036.0,[dream pop],...,Depression Cherry,2015-08-28,9,album,2015,8,28,Friday,5.34,05:20
6,41zXlQxzTi6cGAjpOXyLYH,idontwannabeyouanymore,2,78,203569,False,Billie Eilish,90.0,118692183.0,[],...,dont smile at me,2017-12-22,9,single,2017,12,22,Friday,3.39,03:23

**Creating the popularity tier column and the followers bin**

In [ ]:
pop_bins = [-1, 33, 66, 100]
pop_labels = ['Low', 'Medium', 'High']

df['track_popularity_tier'] = pd.cut(df['track_popularity'], bins=pop_bins, labels=pop_labels)
df['artist_popularity_tier'] = pd.cut(df['artist_popularity'], bins=pop_bins, labels=pop_labels)

In [ ]:
#Creating artist Followers bin column
follower_bins = [-1, 100000, 1000000, 10000000, float('inf')]
follower_labels = ['< 100K', '100K–1M', '1M–10M', '10M+']

df['artist_follower_bin'] = pd.cut(df['artist_followers'], bins=follower_bins, labels=follower_labels)

In [ ]:
df.head(7)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,...,album_type,release_year,release_month,release_day,release_day_name,track_duration_min,track_duration_mmss,track_popularity_tier,artist_popularity_tier,artist_follower_bin
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,[pop],...,compilation,2009,11,9,Monday,3.55,03:33,Medium,High,10M+
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,[stutter house],...,single,2023,1,13,Friday,2.65,02:38,High,High,100K–1M
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],...,album,2021,4,9,Friday,3.76,03:45,Medium,High,10M+
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],...,album,2021,7,30,Friday,2.64,02:38,High,High,10M+
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],...,album,2010,1,1,Friday,4.45,04:27,Medium,High,10M+
5,7H0ya83CMmgFcOhw0UB6ow,Space Song,3,77,320466,False,Beach House,72.0,2803036.0,[dream pop],...,album,2015,8,28,Friday,5.34,05:20,High,High,1M–10M
6,41zXlQxzTi6cGAjpOXyLYH,idontwannabeyouanymore,2,78,203569,False,Billie Eilish,90.0,118692183.0,[],...,single,2017,12,22,Friday,3.39,03:23,High,High,10M+

In [ ]:
df.columns.tolist()

['track_id',
 'track_name',
 'track_number',
 'track_popularity',
 'track_duration_ms',
 'explicit',
 'artist_name',
 'artist_popularity',
 'artist_followers',
 'artist_genres',
 'album_id',
 'album_name',
 'album_release_date',
 'album_total_tracks',
 'album_type',
 'release_year',
 'release_month',
 'release_day',
 'release_day_name',
 'track_duration_min',
 'track_duration_mmss',
 'track_popularity_tier',
 'artist_popularity_tier',
 'artist_follower_bin']

In [ ]:
from google.colab import files

# Save the DataFrame to a CSV file
df.to_csv('cleaned_spotify_data.csv', index=False)

# Trigger automatic download to your computer
files.download('cleaned_spotify_data.csv')